apiVersion: release-notes/v2
kind: feature
area: security
issue:
  - 24554

# releaseNotes is a markdown listing of any user facing changes. This will appear in the
# release notes.
releaseNotes:
- |
  **Added** Enable the workload cert rotate automatically in VM
