apiVersion: release-notes/v2
kind: feature
area: traffic-management

# issue is a list of GitHub issues resolved in this note.
issue:
  - 11130

releaseNotes:
- |
  **Added** config option `values.global.proxy.holdApplicationUntilProxyStarts`,
  which causes the sidecar injector to inject the sidecar at the start of the
  pod's container list and configures it to block the start of all other
  containers until the proxy is ready.  This option is disabled by default.
