apiVersion: release-notes/v2
kind: feature
area: security
issue:
  - 27606

releaseNotes:
- |
  **Added** Experimental Feature support allowing Istiod to integrate with external certificate authorities using Kubernetes CSR API (>=1.18 only). 
