apiVersion: release-notes/v2
kind: bug-fix
area: istioctl
issue:
  - 29608
# releaseNotes is a markdown listing of any user facing changes. This will appear in the
# release notes.
releaseNotes:
  - |
    **Fixed** empty service ports for customized gateway.
