apiVersion: release-notes/v2
kind: feature
area: istioctl

issue:
  - https://github.com/istio/istio/issues/34411

releaseNotes:
  - |
    **Added** two mutually-exclusive flags to `istioctl x workload entry configure`

    * `--internal-ip` configures the VM workload with a private IP address used for workload auto registration and health probes.
    * `--external-ip` configures the VM workload with a public IP address used for workload auto registration. Meanwhile, it configures health probes to be performed through localhost. By setting the environment variable `REWRITE_PROBE_LEGACY_LOCALHOST_DESTINATION` to true.
