apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
  - 33405
releaseNotes:
  - |
    **Fixed** a bug where multiple gateways on the same port with `SIMPLE` and `PASSTHROUGH` modes is not working correctly.