apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
  - 34944

releaseNotes:
- |
  **Fixed** `DestinationRule` updates not triggering an update for `AUTO_PASSTHROUGH` listeners on gateways.
