apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
- |
  **Added** support for sending unready endpoints also to Envoy. This will be useful when slow start mode in Envoy is enabled.
  This can be disabled by setting PILOT_SEND_UNHEALTHY_ENDPOINTS to false.
