apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
  - https://github.com/istio/istio/issues/36462

releaseNotes:
  - |
    **Fixed** an issue where specifying conflict protocols for a service target port
    will cause unstable protocol selection for that port.
