apiVersion: release-notes/v2
kind: feature
area: istioctl
issue:
  - 37415
releaseNotes:
- |
  **Added** a new analyzer for envoy filter patch operations to provide warnings when relative patch operations are used without a priority set which can cause envoyFilters not to be applied correctly.
