apiVersion: release-notes/v2
kind: bug-fix
area: telemetry
issue:
  - https://github.com/istio/istio/issues/37667
releaseNotes:
  - |
    **Fixed** an issue where when enabling Stackdriver metrics collection with the Telemetry API, logging was incorrectly enabled in certain scenarios.
