apiVersion: release-notes/v2
kind: feature
area: telemetry
issue: []
releaseNotes:
- |
  **Added** support for tracing WorkloadMode in Telemetry API. This will allow customization of tracing behavior based on traffic direction.
