apiVersion: release-notes/v2
kind: feature
area: traffic-management

releaseNotes:
  - |
    **Updated** pilot discovery allow unknown flags for backward-compatibility, if an unknown flag passes, no error or warning will be logged.
