apiVersion: release-notes/v2
kind: feature
area: telemetry

releaseNotes:
  - |
    **Added** initial flag-protected support for exporting canonical service labels for ServiceEntry resources with a location of MESH_EXTERNAL.
