apiVersion: release-notes/v2
kind: feature
area: extensibility
issue: []
releaseNotes:
  - |
    **Added** the wasm cache related parameters are now configurable with the env var of istio-agent: WASM_MODULE_EXPIRY, WASM_PURGE_INTERVAL, WASM_HTTP_REQUEST_TIMEOUT, WASM_HTTP_REQUEST_MAX_RETRIES