apiVersion: release-notes/v2
kind: feature
area: installation

releaseNotes:
- |
  **Improved** populate `--log_output_level` and `--log_as_json` to `istio-init` container as they are in `istio-proxy`
