apiVersion: release-notes/v2
kind: feature
area: traffic-management

issue:
  - 40919

releaseNotes:
  - |
    **Added** Allow creating inbound listeners for service ports and sidecar
    and ingress listener both using environment variable
    PILOT_ALLOW_SIDECAR_SERVICE_INBOUND_LISTENER_MERGE.
    This way traffic for service port is not sent via pass-through tcp even
    though its regular http traffic when sidecar ingress listener is defined.
    In case same port number is defined in both sidecar ingress and service,
    sidecar always takes precedence.
