apiVersion: release-notes/v2
kind: bug-fix
area: installation
issue:
  - https://github.com/istio/istio/issues/40984
releaseNotes:
  - |
    **Fixed** an issue when auto.sidecar-injector.istio.io namespaceSelector caused problems with cluster maintenance.