apiVersion: release-notes/v2
kind: feature
area: installation

releaseNotes:
- |
  **Added** Add support for allowing CSR signers via Helm installation

docs:
  - "https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/#deploy-istio-with-default-cert-signer-info"
