apiVersion: release-notes/v2
kind: bug-fix
area: istioctl
issue:
  - https://github.com/istio/istio/issues/42831
  - 42831
releaseNotes:
- |
  **Fixed** the issue where istioctl analyze was throwing SIGSEGV when optional field 'filter'
  was missing under EnvoyFilter.ListenerMatch.FilterChainMatch section.
