apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
  - 44151
releaseNotes:
  - |
    **Fixed** The `dns_upstream_failures_total` metric was mistakenly deleted in the previous release.
