apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
- 44385
releaseNotes:
- |
  **Fixed** an issue where `Istio Gateway` (Envoy) would crash due to a duplicate `istio_authn` network filter in the Envoy filter chain.
