apiVersion: release-notes/v2
kind: feature
area: networking
issue: [31038]
releaseNotes:
- |
  **Fixed** an issue causing an alternative Envoy binary to be included in the docker image. The binaries are functionally equivalent.
