apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
- 39736
releaseNotes:
- |
  **Fixed** an issue causing rejected configuration when using `STATIC` ServiceEntries with `PASSTHROUGH` DestinationRules.