apiVersion: release-notes/v2
kind: feature
area: installation

issue:
  - https://github.com/istio/istio/issues/40427

docs:
 - '[reference] https://istio.io/latest/docs/reference/commands/pilot-discovery/'

releaseNotes:
- |
  **Added** an `ENABLE_LEADER_ELECTION=false` feature flag for pilot-discovery
  to disable leader election when using a single replica of istiod.

