apiVersion: release-notes/v2
kind: feature
area: networking
issue:
- 30309
releaseNotes:
- |
  **Fixed** an issue causing [DNS proxying](/docs/ops/configuration/traffic-management/dns-proxy/) to not work
  when using a DNS resolver on localhost.
