apiVersion: release-notes/v2
kind: feature
area: istioctl
releaseNotes:
  - |
    **Improved** destination rule ca analyzer to show exact error line when using `istioctl analyze`,
    otherwise it will show the first line of its yaml configuration chunk.
