apiVersion: release-notes/v2
kind: bug-fix
area: telemetry
issue:
- 31270
releaseNotes:
- |
  **Fixed** an issue where envoy does not start up properly when
  duplicated extra stats tags are configured.
