apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issues:
- 36284
releaseNotes:
- |
  **Fixed** an issue where `EnvoyFilter` with ANY patch context will skip adding new clusters and listeners at gateway.
