apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
- |
  **Upgraded** the gateway-api integration to read `v1beta1` resources for `ReferenceGrant`, `Gateway`, and `GatewayClass`. Users of the gateway-api must be on v0.6.0+ before upgrading Istio. `istioctl x precheck` can detect this issue before upgrading.
