apiVersion: release-notes/v2

kind: feature
area: traffic-management

# issue is a list of GitHub issues resolved in this note.
# If issue is not in the current repo, specify its full URL instead.
issue:
  - https://github.com/istio/istio/pull/43103

# releaseNotes is a markdown listing of any user facing changes. This will appear in the
# release notes.
releaseNotes:
- |
  **Improved** Gateway naming conventions to be concatenation of `Name` and `GatewayClassName`. 
  Deployment also now deploys with its own Service Account, rather than using the `default` token. 
  Naming convention affects name of Deployment, Service and Service Account.

# upgradeNotes is a markdown listing of any changes that will affect the upgrade
# process. This will appear in the release notes.
upgradeNotes:
  - title: Gateway naming scheme updated
    content: |
      If you are using the [Kubernetes Gateway](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.Gateway)
      to manage your istio gateways, the names of the Kubernetes Deployment and Service has been modified, and the default Service Account used
      has switched to used its own token. The `gateway.istio.io/name-override` and `gateway.istio.io/service-account` annotations can be used to
      continue using the old convention during upgrades.