apiVersion: release-notes/v2
kind: feature
area: installation

# issue is a list of GitHub issues resolved in this note.
issue: []

docs: []

releaseNotes:
- |
  **Added** values to the Istio Pilot Helm charts for configuring affinity rules and tolerations on the Deployment.  Can be used for better placement of Istio pilot workloads.

upgradeNotes: []

securityNotes: []
