apiVersion: release-notes/v2
kind: feature
area: security

# issue is a list of GitHub issues resolved in this note.
issue: []

docs: []

releaseNotes:
- |
  **Added** values to the Istio Gateway Helm charts for configuring annotations on the ServiceAccount.  Can be used to enable [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) on AWS EKS.

upgradeNotes: []

securityNotes: []
