apiVersion: release-notes/v2
kind: feature
area: installation
releaseNotes:
  - |
    **Added** configurable node affinity to istio-cni values.yaml. Can be used to allow excluding istio-cni from being scheduled on specific nodes.