apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
releaseNotes:
- |
  **Improved** service conflict resolution to favor Kubernetes Services over ServiceEntries with the same hostname.
