apiVersion: release-notes/v2
kind: bug-fix
area: security
releaseNotes:
- |
  **Improved** TLS configuration on sidecar server side inbound paths to enforce TLSv2 version along with recommended cipher suites.
               If this is not needed or creates problems with non Envoy clients, it can disabled by setting env variable "PILOT_SIDECAR_ENABLE_INBOUND_TLS_V2" to false.
