apiVersion: release-notes/v2
kind: feature
area: telemetry
issue:
  - 28801

releaseNotes:
- |
  **Added** canonical service tags to Envoy-generated trace spans.
upgradeNotes:
  - title: Service Tags added to trace spans
    content: |
      Istio now configures Envoy to include tags identifying the canonical service for a workload in generated trace spans.

      This will lead to a small increase in storage per span for tracing backends.

      To disable these additional tags, modify the 'istiod' deployment to set an environment variable of `PILOT_ENABLE_ISTIO_TAGS=false`.