apiVersion: release-notes/v2
kind: feature
area: networking
issue:
  - 27179
releaseNotes:
  - |
    **Added** support for warnings to the validation webhook, allowing deprecated feature usage to be reported. This is only supported in Kubernetes 1.19+.
