apiVersion: release-notes/v2
kind: feature
area: extensibility
issue: []
releaseNotes:
  - |
    **Added** allow all insecure servers when one of the host name in the environment variable WASM_INSECURE_REGISTRIES is *.
