{{ $gateway := index .Values "gateways" "canal-controller" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $gateway.name }}-clusterrole{{- if not (eq .Values.revision "")}}-{{ .Values.revision }}{{- end }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: canal-controller
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "create", "get", "list", "watch", "update" ]
  - apiGroups: [ "networking.istio.io" ]
    resources: [ "gateways", "virtualservices" ]
    verbs: [ "get", "list", "watch", "patch" ]
---