apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    base:
      enabled: true

    pilot:
      enabled: true
      hub: docker.io/istio/
      tag: 1.15.0

    ingressGateways:
    - name: istio-ingressgateway
      enabled: false

    acmg:
      enabled: true
      hub: acmg-registry.us-west-1.cr.aliyuncs.com/istio-testing
      tag: latest

    acmgGateway:
      enabled: true
      hub: docker.io/istio/
      tag: 1.15.0