// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by bpf2go; DO NOT EDIT.

package server

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadAcmg_redirect returns the embedded CollectionSpec for acmg_redirect.
func loadAcmg_redirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Acmg_redirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load acmg_redirect: %w", err)
	}

	return spec, err
}

// loadAcmg_redirectObjects loads acmg_redirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*acmg_redirectObjects
//	*acmg_redirectPrograms
//	*acmg_redirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAcmg_redirectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAcmg_redirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// acmg_redirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acmg_redirectSpecs struct {
	acmg_redirectProgramSpecs
	acmg_redirectMapSpecs
}

// acmg_redirectSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acmg_redirectProgramSpecs struct {
	AppInbound           *ebpf.ProgramSpec `ebpf:"app_inbound"`
	AppOutbound          *ebpf.ProgramSpec `ebpf:"app_outbound"`
	NodeproxyHostIngress *ebpf.ProgramSpec `ebpf:"nodeproxy_host_ingress"`
	NodeproxyIngress     *ebpf.ProgramSpec `ebpf:"nodeproxy_ingress"`
}

// acmg_redirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acmg_redirectMapSpecs struct {
	AppInfo       *ebpf.MapSpec `ebpf:"app_info"`
	HostIpInfo    *ebpf.MapSpec `ebpf:"host_ip_info"`
	LogLevel      *ebpf.MapSpec `ebpf:"log_level"`
	NodeproxyInfo *ebpf.MapSpec `ebpf:"nodeproxy_info"`
}

// acmg_redirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAcmg_redirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type acmg_redirectObjects struct {
	acmg_redirectPrograms
	acmg_redirectMaps
}

func (o *acmg_redirectObjects) Close() error {
	return _Acmg_redirectClose(
		&o.acmg_redirectPrograms,
		&o.acmg_redirectMaps,
	)
}

// acmg_redirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAcmg_redirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type acmg_redirectMaps struct {
	AppInfo       *ebpf.Map `ebpf:"app_info"`
	HostIpInfo    *ebpf.Map `ebpf:"host_ip_info"`
	LogLevel      *ebpf.Map `ebpf:"log_level"`
	NodeproxyInfo *ebpf.Map `ebpf:"nodeproxy_info"`
}

func (m *acmg_redirectMaps) Close() error {
	return _Acmg_redirectClose(
		m.AppInfo,
		m.HostIpInfo,
		m.LogLevel,
		m.NodeproxyInfo,
	)
}

// acmg_redirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAcmg_redirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type acmg_redirectPrograms struct {
	AppInbound           *ebpf.Program `ebpf:"app_inbound"`
	AppOutbound          *ebpf.Program `ebpf:"app_outbound"`
	NodeproxyHostIngress *ebpf.Program `ebpf:"nodeproxy_host_ingress"`
	NodeproxyIngress     *ebpf.Program `ebpf:"nodeproxy_ingress"`
}

func (p *acmg_redirectPrograms) Close() error {
	return _Acmg_redirectClose(
		p.AppInbound,
		p.AppOutbound,
		p.NodeproxyHostIngress,
		p.NodeproxyIngress,
	)
}

func _Acmg_redirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed acmg_redirect_bpf.o
var _Acmg_redirectBytes []byte
